bibtex:
    logFile: log
    logLevel: debug
    defaultLang: en
    biblatexProperty: https://vocabs.acdh.oeaw.ac.at/schema#hasCustomCitation
    etal: etal
    mapping:
        person:
            name: https://vocabs.acdh.oeaw.ac.at/schema#hasFirstName
            surname: https://vocabs.acdh.oeaw.ac.at/schema#hasLastName
            label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
        key:
            actors:
            - https://vocabs.acdh.oeaw.ac.at/schema#hasEditor
            - https://vocabs.acdh.oeaw.ac.at/schema#hasAuthor
            - https://vocabs.acdh.oeaw.ac.at/schema#hasCreator
            - https://vocabs.acdh.oeaw.ac.at/schema#hasPrincipalInvestigator
            - https://vocabs.acdh.oeaw.ac.at/schema#hasContributor
            maxActors: 2
            year: https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate
        https://vocabs.acdh.oeaw.ac.at/schema#Resource:
            # there are three types of mapping descriptions
            # 1. bibtexProperty: rdfPropertyUri
            #    maps to a first literal value of a given property (preferably in the defaultLang)
            # 2. bibtexProperty: [list, of, rdf, property, URIs]
            #    maps to a coma-separated list of all values of listed properties (preferably in the defaultLang)
            # 2. bibtexProperty:
            #      type: const/currentDate/eprint/literal/person/url (default literal)
            #      src: resource/topCollection (default resource)
            #      properties: [list, of, rdf, property, URIs]
            #      prefNmsp: preferred value namespace for type "url"
            #                when provided only single value is returned, preferably matching the given prefix
            #      value: value when type "const"
            type: incollection
            title: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
            date: https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate
            publisher: https://vocabs.acdh.oeaw.ac.at/schema#hasHosting
            eprint:
                type: eprint
                properties:
                - https://vocabs.acdh.oeaw.ac.at/schema#hasPid
            eprinttype:
                type: const
                value: hdl
            url: 
                type: url
                prefNmsp: https://hdl.handle.net/
                properties: 
                - https://vocabs.acdh.oeaw.ac.at/schema#hasPid
                - https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
            urldate:
                type: currentDate
            editor: https://vocabs.acdh.oeaw.ac.at/schema#hasEditor
            author: 
                type: person
                properties:
                - https://vocabs.acdh.oeaw.ac.at/schema#hasAuthor
                - https://vocabs.acdh.oeaw.ac.at/schema#hasCreator
                - https://vocabs.acdh.oeaw.ac.at/schema#hasPrincipalInvestigator
            version: https://vocabs.acdh.oeaw.ac.at/schema#hasVersion
            language: https://vocabs.acdh.oeaw.ac.at/schema#hasLanguage
            editora: https://vocabs.acdh.oeaw.ac.at/schema#hasDigitisingAgent
            editoratype: 
                type: const
                value: compiler
            booktitle:
                type: literal
                src: topCollection
                properties:
                - https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
            bookauthor: # of the TopCollection
                type: person
                src: topCollection
                properties:
                - https://vocabs.acdh.oeaw.ac.at/schema#hasAuthor
                - https://vocabs.acdh.oeaw.ac.at/schema#hasCreator
                - https://vocabs.acdh.oeaw.ac.at/schema#hasPrincipalInvestigator
            note: https://vocabs.acdh.oeaw.ac.at/schema#hasHash
            keywords:
            - https://vocabs.acdh.oeaw.ac.at/schema#hasSubject
            - https://vocabs.acdh.oeaw.ac.at/schema#hasRelatedDiscipline
            - https://vocabs.acdh.oeaw.ac.at/schema#hasSpatialCoverage
            abstract: https://vocabs.acdh.oeaw.ac.at/schema#hasDescription
rest:
    urlBase: https://arche.acdh.oeaw.ac.at
    pathBase: /api/
    headers:
        metadataReadMode: X-METADATA-READ-MODE
        metadataParentProperty: X-PARENT-PROPERTY
        metadataWriteMode: X-METADATA-WRITE-MODE
        transactionId: X-TRANSACTION-ID
schema:
    id: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    parent: https://vocabs.acdh.oeaw.ac.at/schema#isPartOf
    label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    searchMatch: search://match
    searchCount: search://count
