on: 
  push:
    branches: [zozlak]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # prepare the service config file
          cp build/config/arche.yaml config.yaml
          # install dependencies
          composer update -o
          # run tests
          vendor/bin/phpunit tests
          # build the docker image
          docker build --rm -t acdhch/arche-biblatex .
          # test the docker image
          docker run -d --name arche-biblatex -p 8080:80 acdhch/arche-biblatex
          sleep 5
      - name: integration test
        run: |
          curl -i 'http://127.0.0.1:8080/?id=https%3A%2F%2Fid.acdh.oeaw.ac.at%2Fgtrans'
      # set up dockerhub authorization
      - uses: docker/login-action@v1
        with:
          username: zozlak
          password: ${{ secrets.DOCKERHUBTOKEN }}
      - run: |
          # push to dockerhub
          docker push acdhch/arche-biblatex
          # redeploy on Rancher
          curl -i -X POST "${{ secrets.RANCHERURL }}?action=redeploy" -H "Authorization: Bearer ${{ secrets.RANCHERTOKEN }}"
